import { StyleSheet } from '@react-pdf/renderer';

export const styles = StyleSheet.create({
    page: {
        flexDirection: 'column',
        backgroundColor: '#fff',
        padding: 30,
        position: 'relative',
    },
    logo: {
        position: 'absolute',
        top: 20,
        right: 20,
        width: 100,
        opacity: 0.7,
    },
    section: {
        margin: 10,
        padding: 10,
        flexGrow: 1,
    },
    title: {
        fontSize: 24,
        fontWeight: 'bold',
        marginBottom: 20,
        color: '#111827',
    },
    sectionTitle: {
        fontSize: 18,
        fontWeight: 'bold',
        marginBottom: 15,
        color: '#374151',
    },
    text: {
        fontSize: 12,
        marginBottom: 10,
        color: '#4B5563',
    },
    pageNumber: {
        position: 'absolute',
        fontSize: 10,
        bottom: 20,
        right: 20,
        color: '#6B7280',
    },
    grid: {
        flexDirection: 'row',
        flexWrap: 'wrap',
        gap: 10,
    },
    card: {
        padding: 10,
        backgroundColor: '#F3F4F6',
        borderRadius: 4,
        marginBottom: 10,
    },
    label: {
        fontSize: 10,
        color: '#6B7280',
        marginBottom: 5,
    },
    value: {
        fontSize: 14,
        color: '#111827',
        fontWeight: 'bold',
    },
    recommendationCard: {
        marginBottom: 10,
        padding: 8,
        backgroundColor: '#F3F4F6',
        borderRadius: 4,
    },
    detailsGrid: {
        display: 'flex',
        flexDirection: 'row',
        flexWrap: 'wrap',
        gap: 16,
        marginTop: 10,
    },
    detailsCard: {
        backgroundColor: '#F3F4F6',
        padding: 12,
        borderRadius: 4,
        minWidth: '45%',
    },
    objectivesList: {
        marginTop: 8,
    },
    objectiveItem: {
        fontSize: 11,
        color: '#4B5563',
        marginBottom: 4,
        paddingLeft: 8,
    },
    chartContainer: {
        marginTop: 20,
        height: 300,
        width: '100%',
    },
    chartLegend: {
        flexDirection: 'row',
        gap: 20,
        marginBottom: 15,
    },
    legendItem: {
        flexDirection: 'row',
        alignItems: 'center',
        gap: 5,
    },
    legendColor: {
        width: 12,
        height: 12,
        borderRadius: 2,
    },
    legendText: {
        fontSize: 8,
        color: '#4B5563',
    },
    chartGrid: {
        height: 250,
        flexDirection: 'row',
        justifyContent: 'space-between',
        borderBottomWidth: 1,
        borderBottomColor: '#E5E7EB',
        marginTop: 10,
    },
    yAxis: {
        width: 30,
        height: '100%',
        position: 'absolute',
        left: 0,
    },
    yAxisLabel: {
        fontSize: 8,
        color: '#9CA3AF',
        textAlign: 'right',
        position: 'absolute',
        right: 5,
    },
    xAxis: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        position: 'absolute',
        bottom: -20,
        left: 35,
        right: 0,
    },
    xAxisLabel: {
        fontSize: 8,
        color: '#4B5563',
        textAlign: 'center',
        width: '100%',
    },
    barGroup: {
        flexDirection: 'row',
        alignItems: 'flex-end',
        height: '100%',
        justifyContent: 'center',
        gap: 4,
    },
    bar: {
        flex: 1,
        maxWidth: 25,
        borderRadius: 2,
        display: 'flex',
        alignItems: 'center',
        justifyContent: 'flex-end',
    },
    barValue: {
        fontSize: 10,
        color: '#ffffff',
        textAlign: 'center',
        marginBottom: 5,
        fontWeight: 'bold',
    },
    watermark: {
        position: 'absolute',
        top: '50%',
        left: '50%',
        transform: 'translate(-50%, -50%) rotate(-45deg)',
        fontSize: 60,
        opacity: 0.08,
        color: '#666',
        zIndex: -1,
    },
}); 